Pal 710 ecr push
gchq/Palisade-clients pull request #38
Opened 2020-09-07 12:22 UTC by m78233

2020-09-08 13:55 UTC, pd104923 requested changes

2020-09-08 13:55 UTC, pd104923 commented on clients-cat/pom.xml
> -  ~ distributed under the License is distributed on an "AS IS" BASIS,
Is there a reason this has been removed from the license header?

2020-09-08 15:14 UTC, pd104923 submitted a review, later dismissed

2020-09-09 07:14 UTC, pd104923 requested changes
1 question about the 2nd order dependency update.

2020-09-09 07:14 UTC, pd104923 commented on Jenkinsfile
> +                            READERS_REVISION = "BRANCH-${GIT_BRANCH_NAME_LOWER}-SNAPSHOT"
```suggestion
                    } else {
                        if (COMMON_REVISION == "BRANCH-${GIT_BRANCH_NAME_LOWER}-SNAPSHOT") {
                            sh "mvn -s ${MAVEN_SETTINGS} -D revision=${READERS_REVISION} -D common.revision=${COMMON_REVISION} deploy"
```
If the readers repo doesn't have a branch of the same name then why would the `READERS_REVISION` require the branch name to be in the snapshot? Wouldn't this just need to stay as `SNAPSHOT`? We've already done a deploy of readers using the `SNAPSHOT` revision value.

2020-09-09 08:40 UTC, pd104923 submitted a review, later dismissed
All good now

2020-09-09 09:51 UTC, developer01189998819991197253 submitted a review, later dismissed

2020-09-09 14:32 UTC, pd104923 submitted a review, later dismissed

2020-09-10 09:56 UTC, developer01189998819991197253 approved these changes

2020-09-10 10:28 UTC, dev-958 submitted a review, later dismissed

2020-09-10 16:02 UTC, merged