PAL-939 streaming client
gchq/Palisade-clients pull request #52
Opened 2021-01-27 14:27 UTC by dbz120896

Here is the new java client with streaming onboard. Please take particular attention to the exposed interfaces. The only package accessible should be the main one.

2021-01-27 17:24 UTC, developer01189998819991197253 requested changes
first pass

2021-01-27 17:24 UTC, developer01189998819991197253 commented on client-java/src/main/java/uk/gov/gchq/palisade/client/Client.java
> + * Copyright 2020-2021 Crown Copyright
Replace copyright template with Copyright 2018-2021 Crown Copyright for all Palisade files

2021-01-28 09:28 UTC, dbz120896 commented on client-java/src/unit-tests/java/uk/gov/gchq/palisade/client/abc/WsEndpointFilteredResource.java
> +        LOGGER.debug("<-- CLOSE request received", session.getId());
done

2021-01-28 09:31 UTC, dbz120896 commented on client-java/src/main/java/uk/gov/gchq/palisade/client/MessageType.java
> +    RESOURCE;
I wish Oracle would just allow one way or the other and make the other one an error.
Done.

2021-01-28 09:35 UTC, dbz120896 commented on client-java/src/main/java/uk/gov/gchq/palisade/client/internal/dft/DefaultQueryResponse.java
> +            } while (!leave);
I created the `createMessage` function to reduce complexity as there were too many exits.The check for a `CompleteMessage` should set it to true and then perform an else.
Done

2021-01-28 11:26 UTC, dbz120896 commented on client-java/src/unit-tests/java/uk/gov/gchq/palisade/client/abc/impl/DefaultClientTest.java
> +    }
Deleted.

2021-01-28 11:29 UTC, dbz120896 commented on client-java/src/main/java/uk/gov/gchq/palisade/client/util/Util.java
> +                    result.put(entry.getKey(), repl);
done

2021-01-28 11:30 UTC, dbz120896 commented on client-java/src/main/java/uk/gov/gchq/palisade/client/internal/resource/WebSocketMessage.java
> + * A websocket message is the actuial instance sent/received to/from the
done

2021-01-28 11:31 UTC, dbz120896 commented on NOTICES.md
> +* readers-common ([uk.gov.gchq.palisade:readers-common:0.5.0-20210126.160626-27](https://github.com/gchq/Palisade-readers/tree/develop/readers-common))
Yup, will do.

2021-01-28 11:42 UTC, dbz120896 commented on NOTICES.md
> +* SLF4J API Module ([org.slf4j:slf4j-api:1.7.26](http://www.slf4j.org))
client-java uses 1.7.26. I think other projects in the reactor use previous version. The client-java project has nothing to do with other client projects, so should be split into it's own repository.

2021-01-28 13:44 UTC, dbz120896 commented on client-java/src/unit-tests/java/uk/gov/gchq/palisade/client/internal/download/DownloaderTest.java
> +    void testSuccessfulDownload() throws Exception {
done

2021-01-28 13:44 UTC, dbz120896 commented on client-java/src/unit-tests/java/uk/gov/gchq/palisade/client/internal/resource/ResourceClientTest.java
> +    void testMessageFlow() throws Exception {
done

2021-01-28 14:11 UTC, dbz120896 commented on client-java/src/main/java/uk/gov/gchq/palisade/client/ClientManager.java
> +    }
When running in a prod environment, you will not need to supply a properties object. User/port will be supplied on the url. I've added a test that exercises it.

2021-01-28 14:13 UTC, dbz120896 commented on client-java/src/unit-tests/java/uk/gov/gchq/palisade/client/abc/WsEndpointFilteredResource.java
> +    boolean completeSent = false;
That was a Klingon ;) Removed.

2021-01-28 14:42 UTC, dbz120896 commented on client-java/src/unit-tests/java/uk/gov/gchq/palisade/client/abc/impl/FullTest.java
> +            .subscribe(new FlowableSubscriber<Download>() {
Done

2021-01-28 14:45 UTC, dbz120896 commented on client-java/src/unit-tests/java/uk/gov/gchq/palisade/client/abc/impl/FullTest.java
> +                        throw new IllegalStateException("Got error reading inputstream into byte array", e);
done

2021-01-28 14:53 UTC, dbz120896 commented on client-java/src/unit-tests/java/uk/gov/gchq/palisade/client/abc/impl/FullTest.java
> +    @Disabled
I'll create one...... Done : https://jira.tdx.oneit.gov.uk/browse/PAL-979

2021-01-28 14:54 UTC, dbz120896 commented on client-java/src/main/java/uk/gov/gchq/palisade/client/internal/impl/Configuration.java
> +        // if the url is not set, then we cannot propcess it
done

2021-01-28 14:58 UTC, dbz120896 commented on client-java/src/unit-tests/java/uk/gov/gchq/palisade/client/abc/WsEndpointFilteredResource.java
> +            .putHeader("token", session.get(TOKEN_KEY, String.class).get())
Pretty unlikely, but I've added an `orElseThrow`.

2021-01-28 15:02 UTC, dbz120896 commented on client-java/src/unit-tests/java/uk/gov/gchq/palisade/client/abc/impl/FullTest.java
> +        var properties = Map.<String, String>of(
Java compiler is getting good. Can just do `Map.of()` and it gets `<String,String>`. Done

2021-01-28 15:02 UTC, dbz120896 commented on client-java/src/unit-tests/java/uk/gov/gchq/palisade/client/abc/impl/FullTest.java
> +        var properties = Map.<String, String>of(
done

2021-01-28 15:03 UTC, dbz120896 commented on client-java/src/unit-tests/java/uk/gov/gchq/palisade/client/abc/impl/ConfigurationTest.java
> +        assertThatExceptionOfType(IllegalArgumentException.class).isThrownBy(() -> Configuration.from((String) null));
Did need that as the compiler saw some methods as ambiguous. They are now renamed. I've removed the casts.

2021-01-28 15:09 UTC, dbz120896 commented on client-java/src/unit-tests/java/uk/gov/gchq/palisade/client/abc/impl/ConfigurationTest.java
> +        var actual = expected.merge((Map) null);
done

2021-01-28 15:14 UTC, dbz120896 commented on client-java/src/main/java/uk/gov/gchq/palisade/client/internal/impl/Configuration.java
> +    private static String createrPalisadeUrl(final URI baseUri, final Map<String, Object> properties) {
You have sharp eyes!

2021-01-28 15:15 UTC, dbz120896 commented on client-java/src/main/java/uk/gov/gchq/palisade/client/internal/impl/Configuration.java
> +        final var bldr = new StringBuilder()
Done

2021-01-28 15:16 UTC, dbz120896 commented on client-java/src/main/java/uk/gov/gchq/palisade/client/internal/dft/DefaultClient.java
> + * This client is the default impleentation and responds to the subname of
Done

2021-01-28 15:17 UTC, dbz120896 commented on client-java/src/unit-tests/java/uk/gov/gchq/palisade/client/internal/download/DownloaderTest.java
> +    private static final String BASE_URL = "http://localhost:"; // needs port added befoire use
done

2021-01-28 15:18 UTC, dbz120896 commented on client-java/src/main/java/uk/gov/gchq/palisade/client/Query.java
> +     * @return a {@code CompleteableFuture} containing the result of the query
done

2021-01-28 15:22 UTC, dbz120896 commented on client-java/src/main/java/uk/gov/gchq/palisade/client/Download.java
> +     * @return the inputstream of bytes
done

2021-01-28 15:24 UTC, dbz120896 commented on client-java/src/main/java/uk/gov/gchq/palisade/client/internal/dft/DefaultQueryResponse.java
> +        var flowable = Flowable.<Message>create((final FlowableEmitter<Message> emitter) -> {
removed chevrons completely. done

2021-01-28 15:26 UTC, dbz120896 commented on client-java/src/main/java/uk/gov/gchq/palisade/client/internal/impl/ConfigurationException.java
> +public class ConfigurationException extends ClientException {
`Configuration` now throws this exception which is a subclass of `ClientException`.

2021-02-03 13:40 UTC, closed without merging