Pal 1082 remove resource parent
gchq/Palisade-clients pull request #69
Opened 2021-07-02 14:53 UTC by dev930018

Awaiting on [PAL-1023](https://github.com/gchq/Palisade-clients/pull/67) being merged.

2021-07-08 07:46 UTC, pd104923 submitted a review, later dismissed
1 minor thing and the license changes should be reverted.

2021-07-14 10:03 UTC, developer01189998819991197253 requested changes

2021-07-14 10:03 UTC, developer01189998819991197253 commented on client-java/src/unit-tests/java/uk/gov/gchq/palisade/client/java/internal/download/DownloaderExceptionTest.java
> +                .isEqualTo(400);
```suggestion
                .isEqualTo(expectedCode);
```

2021-07-14 10:03 UTC, developer01189998819991197253 commented on licenses/gnu_lgpl_2.1.html
> +
revert

2021-07-14 10:03 UTC, developer01189998819991197253 commented on licenses/mit_license.html
> -<link type="text/css" rel="stylesheet" href="https://opensource.org/sites/all/themes/bootstrap-business/css/ie8.css?qqdhfs" media="all" />
revert

2021-07-14 15:48 UTC, developer01189998819991197253 approved these changes

2021-07-15 08:39 UTC, merged